name: BIPBOP PHP Client
on: [ push, pull_request ]
jobs:
  library-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl
          coverage: xdebug
          tools: phpunit
      - name: Setup Library
        run: composer install
      - name: Make Tests
        run: phpunit --coverage-text
